# Generated by Django 4.2.13 on 2024-05-22 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0002_remove_chaivarity_image_alter_chaivarity_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivarity',
            name='image',
            field=models.FileField(default='default_image.png', upload_to='chais/'),
        ),
        migrations.AlterField(
            model_name='chaivarity',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 22, 16, 44, 20, 322320, tzinfo=datetime.timezone.utc)),
        ),
    ]
