# Generated by Django 4.2.13 on 2024-06-02 03:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0011_alter_chaivarity_date_added_store_chaireview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaicertificate',
            name='issued_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 3, 35, 29, 556137, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chaireview',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 3, 35, 29, 554125, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chaivarity',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 3, 35, 29, 554125, tzinfo=datetime.timezone.utc)),
        ),
    ]
