# Generated by Django 4.2.13 on 2024-06-02 03:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0012_alter_chaicertificate_issued_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaicertificate',
            name='issued_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 3, 55, 35, 988719, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chaireview',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 3, 55, 35, 987723, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chaivarity',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 2, 3, 55, 35, 986720, tzinfo=datetime.timezone.utc)),
        ),
    ]
