# Generated by Django 4.2.13 on 2024-06-02 04:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0013_alter_chaicertificate_issued_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaicertificate',
            name='issued_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chaireview',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chaivarity',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
